name: Bug
description: Something weird is happening.
title: "[BUG] ADD TITLE HERE"
labels: BUG

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues and none matched.
        required: true
  - type: markdown
    attributes:
      value: |
        # **System Information**
  - type: input
    id: OS
    attributes:
      label: Operating System
      description: What OS are you playing the game on?
    validations:
      required: true
  - type: input
    id: CPU
    attributes:
      label: CPU
      description: Type the CPU name your computer is using. If you are unsure, leave this blank.
  - type: input
    id: GPU
    attributes:
      label: GPU
      description: What GPU are you using to play? If you are unsure, leave this blank.
  - type: input
    id: Storage
    attributes:
      label: Storage
      description: Type information about your storage
  - type: markdown
    attributes:
      value: |
        # **General OutFox Information**
  - type: dropdown
    id: version
    attributes:
      label: Game Version
      description: Which Alpha are you testing?
      options:
        - Alpha 0.4 LTS
        - Alpha V
    validations:
      required: true
  - type: dropdown
    id: gamemode
    attributes:
      label: Game Mode
      description: What Game Mode are you playing on?
      options:
        - I was using the editor!
        - dance
        - pump
        - smx
        - techno
        - be-mu
        - po-mu
        - gddm
        - gdgf
        - gh
        - taiko
        - para
        - kbx
        - ez2
        - ds3ddx
        - maniax
        - stepstage
        - kickbox
    validations:
      required: true
  - type: textarea
    id: theme
    attributes:
      label: Theme
      description: Please let us know what theme (and version) you are using.          
  - type: textarea
    id: Problem
    attributes:
      label: Describe the problem
      description: A clear and concise description of what is happening.
    validations:
      required: true
  - type: textarea
    id: Expected
    attributes:
      label: Describe what should happen
      description: A clear and concise description of what you think should happen.
  - type: markdown
    attributes:
      value: |
        # **Logs and Additional Content**
        #1. Go into the game folder
        #2. Open the Logs folder
        #3. Grab log files of your latest run, "ProjectOutfox.Crash" and "ProjectOutfox.MainLog"

        If you happen to play Non-Portable mode, [check the location of your Contents folder](https://outfox.wiki/user-guide/config/folders/) to find it, and proceed with step #2.

        You can also add any other context or screenshots here.
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log output
